import Foundation

/// The real Codex smoke test consumes metadata generated by the exact Swift implementation shipped in the app.
@main struct ProviderFixture {
    static func main() throws {
        var custom = AIProviderProfile.custom()
        custom.id = "custom-fixture"; custom.name = "Local test provider"; custom.model = "proxy-model"; custom.models = [custom.model]
        custom.baseURL = "http://127.0.0.1:1234/v1"; custom.supportsImages = true
        let values: [CodexJSON] = try [AIProviderProfile.deepSeek, custom].map { profile in
            ["id": .string(profile.id), "model": .string(profile.model), "catalog": profile.catalog(),
             "overrides": .array(try profile.launchOverrides(catalog: URL(fileURLWithPath: "/tmp/fixture-models.json")).map(CodexJSON.string))]
        }
        print(CodexJSON.array(values).pretty)
    }
}
